### PR TITLE
systemd on debian/ubuntu

### PR DESCRIPTION
**Pull request by ayashjorden**
Instead of #60

### CODE REVIEW

**Comment by dwerder** [comment]
Do you mind to add spec tests for that? And at this moment the PR would mean, that all Debian and Ubuntu distros use systemd. Is this the case?

**Comment by ayashjorden** [comment]
Maybe I can change the `$systemd_os` conditional.

I'm thinking about adding a `$service_provider` variable to the server/sentinel constructors and use `case` to determine the script_name, whether init/systemd should be used and the Service provider.

Let me know what you think,
Yarden

**Comment by dwerder** [comment]
Their is a PR for systemd on RHEL #62 . This PR uses cmpversion to exactly specify a distro version. I will merge if the ci is green. Maybe you can orientate on that.

**Comment by dwerder** [comment]
Mostly fixed by f29acea

**Pull request closed without merging**
