### PR TITLE
Add initial cluster support to redis::server

### PR DESCRIPTION
**Pull request by vide**
Hello

with this PR I add basic support for clustering in this module. You still need to run redis-trib.rb to properly initiate the cluster but it's not trivial to puppetize it.
Maybe I should add a check that redis version should be > 3.0?

### CODE REVIEW

**Comment by dwerder** [comment]
Thanks for the PR. A check for the version would be nice. As well as some documentation in the READEM for the ne introduced parameters.

**Comment by dwerder** [comment]
Furthermore you should reopen this PR against develop branch as described in DEVELOP.md

**Comment by vide** [comment]
Thinking it again, about the version check, how is the `$redis::install::redis_version` handled? I mean, I saw the `$redis_2_6_or_greater` variable and I was thinking to do something similar with 3.0 and cluster but, the default `stable` value always returns **true**, and so does `installed` (I guess that every string without a number always return true when passed through `versioncmp`. So for example in the Debian case that would be a problem, because for example in Jessie, by default it only has Redis 2.8. What's your opinion?

**Comment by dwerder** [comment]
To be honest, I have no opinion about that. The variable $redis_2_6_or_greater is just a bad workaround. Maybe a list/map with features for redis versions is a better way.

Have a "global" $redis_major_version (eg: 2.6 , 2.8, 3.0 ...) and make all decissions on that value.

**Pull request closed without merging**
