### PR TITLE
Enable redis cluster (with doc)

### PR DESCRIPTION
**Pull request by vide**
As discussed in #76 I've added doc, made the PR against develop and added another versioncmp hack. I'll try to figure out a better way to manage versions, but right now I think that cluster support is more important

### CODE REVIEW

**Comment by dwerder** [comment]
Can you add the documentation to the README.md, please? Everything else looks fine. And will be merged.

**Comment by vide** [comment]
Absolutely, I was already writing the missing doc in the main README.md, didn't think about it before!

**Comment by vide** [comment]
@dwerder is it ok now?

**Comment by dwerder** [comment]
Perfect.

**Pull request merged**
